### ISSUE TITLE
Importing vocabulary; invalid_reason is empty string instead of NULL

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/ETL-Synthea#73]
Importing vocabulary in postgresql using v5.3.1-updated branch.

After import, all `concept.invalid_reason` without a value are imported as empty string. According to the CDM conventions, an empty invalid reason should be NULL.

Is this a postgres issue or do we have to set NULLs explicitly in [LoadVocabFromCsv.r](https://github.com/OHDSI/ETL-Synthea/blob/master/R/LoadVocabFromCsv.r)?

**Comment by AnthonyMolinaro** [comment]
@MaximMoinat Hi Maxim, thanks for catching this!  

It turns out this isn't limited to PG, but affects all databases.  When using read.csv or data.table::fread, it seems that empty character fields are imported as empty strings, "".  The fix is to convert those into NA in R which will then get properly created  as NULL via DatabaseConnector. I've included this fix in my [PR](https://github.com/OHDSI/ETL-Synthea/pull/77).
