### ISSUE TITLE
Error while CreateCDMTables

### ISSUE THREAD

**Issue by mgabetta** [OHDSI/ETL-Synthea#78]
Hi!
I get this error while executing ETLSyntheaBuilder::CreateCDMTables:

```
Executing DDL from: https://raw.githubusercontent.com/OHDSI/CommonDataModel/v5.3.1/PostgreSQL/OMOP%20CDM%20postgresql%20ddl.txt
Saving DDL in: output/postgresql_5.3.1_ddl.sql
Error in file(file, if (append) "a" else "w")
```

**Comment by AnthonyMolinaro** [comment]
@mgabetta  Hi, thanks for catching this!  It looks like I accidentally excluded the output directory via .gitignore.  I've now added the folder and updated .gitignore.  Please pull Master and let me know how it goes.

**Comment by mgabetta** [comment]
Hi!
same issue (from the R command line) after:
- > remove.packages("ETLSyntheaBuilder")
- devtools::install_github("OHDSI/ETL-Synthea")

I've tried cloning the repo and here's what I found (output folder present but empty):

![image](https://user-images.githubusercontent.com/5736000/107021617-a8d8a580-67a4-11eb-9abb-cebbb531de75.png)

**Comment by mgabetta** [comment]
ok got it.
I thought that with R (devtools::install_github("OHDSI/ETL-Synthea")) it wasn't necessary to  git clone the repo locally.
after cloning and running R from the project root, it works!
One question: is it normal with "devtools::install_github" the need of having the repo locally downloaded?

**Comment by AnthonyMolinaro** [comment]
@mgabetta Another good catch!  The problem is not with install_github, the problem is with the author of this code. ;)
The output directory is created as part of the package, but the code doesn't specify an absolute path, just a relative one.  So, when you execute the function, it's looking for an output directory relative to your pwd.  I've just updated Master to create an output directory if one doesn't exist. Thanks to @fdefalco for the good suggestion.
